title: Eleventy Sveltia CMS Starter
description: A template for building a fast Eleventy blog with Sveltia CMS, with deployment to Netlify
url: https://694e8fab3893fa0008175b31--test-cms-11ty.netlify.app
